'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property BTC_Position() As Global.System.Drawing.Point
            Get
                Return CType(Me("BTC_Position"),Global.System.Drawing.Point)
            End Get
            Set
                Me("BTC_Position") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property ETH_Position() As Global.System.Drawing.Point
            Get
                Return CType(Me("ETH_Position"),Global.System.Drawing.Point)
            End Get
            Set
                Me("ETH_Position") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property LTC_Position() As Global.System.Drawing.Point
            Get
                Return CType(Me("LTC_Position"),Global.System.Drawing.Point)
            End Get
            Set
                Me("LTC_Position") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property DOGE_Position() As Global.System.Drawing.Point
            Get
                Return CType(Me("DOGE_Position"),Global.System.Drawing.Point)
            End Get
            Set
                Me("DOGE_Position") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property XMR_Position() As Global.System.Drawing.Point
            Get
                Return CType(Me("XMR_Position"),Global.System.Drawing.Point)
            End Get
            Set
                Me("XMR_Position") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property BCH_Position() As Global.System.Drawing.Point
            Get
                Return CType(Me("BCH_Position"),Global.System.Drawing.Point)
            End Get
            Set
                Me("BCH_Position") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property XRP_Position() As Global.System.Drawing.Point
            Get
                Return CType(Me("XRP_Position"),Global.System.Drawing.Point)
            End Get
            Set
                Me("XRP_Position") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property ADA_Position() As Global.System.Drawing.Point
            Get
                Return CType(Me("ADA_Position"),Global.System.Drawing.Point)
            End Get
            Set
                Me("ADA_Position") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property NANO_Position() As Global.System.Drawing.Point
            Get
                Return CType(Me("NANO_Position"),Global.System.Drawing.Point)
            End Get
            Set
                Me("NANO_Position") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BTC_Ativate() As Boolean
            Get
                Return CType(Me("BTC_Ativate"),Boolean)
            End Get
            Set
                Me("BTC_Ativate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ETH_Ativate() As Boolean
            Get
                Return CType(Me("ETH_Ativate"),Boolean)
            End Get
            Set
                Me("ETH_Ativate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LTC_Ativate() As Boolean
            Get
                Return CType(Me("LTC_Ativate"),Boolean)
            End Get
            Set
                Me("LTC_Ativate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DOGE_Ativate() As Boolean
            Get
                Return CType(Me("DOGE_Ativate"),Boolean)
            End Get
            Set
                Me("DOGE_Ativate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property XMR_Ativate() As Boolean
            Get
                Return CType(Me("XMR_Ativate"),Boolean)
            End Get
            Set
                Me("XMR_Ativate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BCH_Ativate() As Boolean
            Get
                Return CType(Me("BCH_Ativate"),Boolean)
            End Get
            Set
                Me("BCH_Ativate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property XRP_Ativate() As Boolean
            Get
                Return CType(Me("XRP_Ativate"),Boolean)
            End Get
            Set
                Me("XRP_Ativate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ADA_Ativate() As Boolean
            Get
                Return CType(Me("ADA_Ativate"),Boolean)
            End Get
            Set
                Me("ADA_Ativate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NANO_Ativate() As Boolean
            Get
                Return CType(Me("NANO_Ativate"),Boolean)
            End Get
            Set
                Me("NANO_Ativate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Night_And_Day() As Boolean
            Get
                Return CType(Me("Night_And_Day"),Boolean)
            End Get
            Set
                Me("Night_And_Day") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Config_Hide() As Boolean
            Get
                Return CType(Me("Config_Hide"),Boolean)
            End Get
            Set
                Me("Config_Hide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ADA_Lock() As Boolean
            Get
                Return CType(Me("ADA_Lock"),Boolean)
            End Get
            Set
                Me("ADA_Lock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BCH_Lock() As Boolean
            Get
                Return CType(Me("BCH_Lock"),Boolean)
            End Get
            Set
                Me("BCH_Lock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BTC_Lock() As Boolean
            Get
                Return CType(Me("BTC_Lock"),Boolean)
            End Get
            Set
                Me("BTC_Lock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DOGE_Lock() As Boolean
            Get
                Return CType(Me("DOGE_Lock"),Boolean)
            End Get
            Set
                Me("DOGE_Lock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ETH_Lock() As Boolean
            Get
                Return CType(Me("ETH_Lock"),Boolean)
            End Get
            Set
                Me("ETH_Lock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LTC_Lock() As Boolean
            Get
                Return CType(Me("LTC_Lock"),Boolean)
            End Get
            Set
                Me("LTC_Lock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NANO_Lock() As Boolean
            Get
                Return CType(Me("NANO_Lock"),Boolean)
            End Get
            Set
                Me("NANO_Lock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property XMR_Lock() As Boolean
            Get
                Return CType(Me("XMR_Lock"),Boolean)
            End Get
            Set
                Me("XMR_Lock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property XRP_Lock() As Boolean
            Get
                Return CType(Me("XRP_Lock"),Boolean)
            End Get
            Set
                Me("XRP_Lock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Start_Windows() As Boolean
            Get
                Return CType(Me("Start_Windows"),Boolean)
            End Get
            Set
                Me("Start_Windows") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hide_Tray() As Boolean
            Get
                Return CType(Me("Hide_Tray"),Boolean)
            End Get
            Set
                Me("Hide_Tray") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Sound() As Boolean
            Get
                Return CType(Me("Sound"),Boolean)
            End Get
            Set
                Me("Sound") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Binance")>  _
        Public Property Exchange() As String
            Get
                Return CType(Me("Exchange"),String)
            End Get
            Set
                Me("Exchange") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property My_IP() As Boolean
            Get
                Return CType(Me("My_IP"),Boolean)
            End Get
            Set
                Me("My_IP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property My_IP_Position() As Global.System.Drawing.Point
            Get
                Return CType(Me("My_IP_Position"),Global.System.Drawing.Point)
            End Get
            Set
                Me("My_IP_Position") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property My_IP_Lock() As Boolean
            Get
                Return CType(Me("My_IP_Lock"),Boolean)
            End Get
            Set
                Me("My_IP_Lock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property My_IP_Activate() As Boolean
            Get
                Return CType(Me("My_IP_Activate"),Boolean)
            End Get
            Set
                Me("My_IP_Activate") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.My_Crypto_Gadgets.My.MySettings
            Get
                Return Global.My_Crypto_Gadgets.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
